### ISSUE TITLE
Building from git master broken after https://github.com/bitwarden/browser/commit/9fce5147e70741c115af61bf9836187c1b92a6c9

### ISSUE THREAD

**Issue by glitsj16** [bitwarden/browser#1156]
After https://github.com/bitwarden/browser/commit/9fce5147e70741c115af61bf9836187c1b92a6c9 I see this when building:

```
$ npm  run dist:firefox
...
> gulp build && cross-env NODE_ENV=production webpack

[23:34:21] Using gulpfile ~/.buildzone/bitwarden/gulpfile.js
[23:34:21] Starting 'build'...
[23:34:23] Finished 'build' after 1.84 s
clean-webpack-plugin: /home/glitsj16/.buildzone/bitwarden/build/* has been removed.
Hash: e65c5a5bfddc06c9905f
Version: webpack 4.29.0
Time: 51981ms
Built at: 27/02/2020 23.35.20
 10 assets
Entrypoint popup/main = popup/main.js
Entrypoint background = background.js
Entrypoint content/autofill = content/autofill.js
Entrypoint content/autofiller = content/autofiller.js
Entrypoint content/notificationBar = content/notificationBar.js
Entrypoint content/shortcuts = content/shortcuts.js
Entrypoint notification/bar = notification/bar.js notification/bar.css
[0] ./src/popup/main.ts 0 bytes {6} [built]
[1] ./src/background.ts 0 bytes {0} [built]
[2] ./src/content/autofill.js 41.7 KiB {1} [built]
[3] ./src/content/autofiller.ts 0 bytes {2} [built]
[4] ./src/content/notificationBar.ts 0 bytes {3} [built]
[5] ./src/content/shortcuts.ts 0 bytes {4} [built]
[6] ./src/notification/bar.js 5.27 KiB {5} [built]
[7] ./src/notification/bar.scss 41 bytes {5} [built]

ERROR in src/background/main.background.ts(178,42): error TS2554: Expected 3 arguments, but got 2.

Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js!src/notification/bar.scss:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    [0] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/notification/bar.scss 1.54 KiB {0} [built]
        + 1 hidden module
Child html-webpack-plugin for "background.html":
     1 asset
    Entrypoint undefined = background.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/background.html 101 bytes {0} [built]
Child html-webpack-plugin for "notification/bar.html":
     1 asset
    Entrypoint undefined = notification/bar.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/notification/bar.html 2.79 KiB {0} [built]
Child html-webpack-plugin for "popup/index.html":
     1 asset
    Entrypoint undefined = popup/index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/popup/index.html 405 bytes {0} [built]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bitwarden-browser@0.0.0 build:prod: `gulp build && cross-env NODE_ENV=production webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the bitwarden-browser@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/glitsj16/.npm/_logs/2020-02-27T22_35_20_591Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bitwarden-browser@0.0.0 dist:firefox: `npm run build:prod && gulp dist:firefox`
npm ERR! Exit status 2

npm ERR! Failed at the bitwarden-browser@0.0.0 dist:firefox script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/glitsj16/.npm/_logs/2020-02-27T22_35_20_631Z-debug.log
```

> ERROR in src/background/main.background.ts(178,42): error TS2554: Expected 3 arguments, but got 2.

Is it possible the jslib update broke something?

**Comment by kspearrin** [comment]
We just need https://github.com/bitwarden/browser/pull/1155 merged @vincentsalucci
